#!/bin/bash
# Put a `dsh` executable for a given source checkout on PATH.
#
# The verification scripts call `dsh` bare, which assumes a CLI already on PATH. Locally
# that is usually a wrapper the maintainer made; in CI nothing exists yet. This creates
# the same two-line wrapper so both paths behave identically.
#
# Usage: bash scripts/install-dsh-shim.sh <path-to-deepseek-harness> <bin-dir>
set -euo pipefail

CHECKOUT="${1:-}"
BINDIR="${2:-}"
if [[ -z "$CHECKOUT" || ! -d "$CHECKOUT" ]]; then
  echo "usage: bash scripts/install-dsh-shim.sh <path-to-deepseek-harness> <bin-dir>" >&2
  exit 2
fi
if [[ -z "$BINDIR" ]]; then
  echo "a bin directory is required as the second argument" >&2
  exit 2
fi

CLI="$CHECKOUT/apps/cli/lib/bin.js"
if [[ ! -f "$CLI" ]]; then
  echo "no built CLI at $CLI — run 'pnpm run build' in the checkout first" >&2
  exit 3
fi

mkdir -p "$BINDIR"
cat > "$BINDIR/dsh" <<EOF
#!/bin/sh
# Generated by dsh-exploration-kit scripts/install-dsh-shim.sh
# Runs the built CLI of the checkout at: $CHECKOUT
exec node "$CLI" "\$@"
EOF
chmod +x "$BINDIR/dsh"
echo "installed $BINDIR/dsh -> $CLI"
"$BINDIR/dsh" --version 2>/dev/null || echo "(version check skipped)"
